## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/nanobrowser/nanobrowser/discussions
    about: Please ask and answer questions here to keep the issue tracker clean.